<?php
/**
 * @category    Scandiweb
 * @package     Scandiweb/Slider
 * @author      Rihards Ratke <info@scandiweb.com>
 * @copyright   Copyright (c) 2018 Scandiweb, Inc (https://scandiweb.com)
 * @license     http://opensource.org/licenses/OSL-3.0 The Open Software License 3.0 (OSL-3.0)
 */
?>
<script type="text/x-magento-init">
{
   "body":{
      "Scandiweb_Slider/js/canvasMapWiget":{}
   }
}
</script>
